ALTER TABLE t_p16851207_avito_clone_improvem.ads
  ADD COLUMN IF NOT EXISTS subcategory VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS condition VARCHAR(20) NULL DEFAULT 'used',
  ADD COLUMN IF NOT EXISTS quantity INTEGER NOT NULL DEFAULT 1;
